import type { WorkflowView } from "@/domain/workflow-view";

/**
 * Project-owned operational workflow canvases (migrated from `/ecosystem`).
 * Keys are project slugs; diagram data is verbatim from the ecosystem inventory.
 */

const workflowRenovate: WorkflowView = {
  id: "workflow-renovate",
  title: "Renovate governance ladder",
  summary:
    "Classify → investigate or maintainer path → merge gates. Walkthrough of the Codenames Renovate governance ladder.",
  talkTrack:
    "Walk Classify → Route → Investigate or Maintainer → Merge gates. The classifier emits a packet and never merges; the maintainer may merge only when policy and checks allow.",
  nodes: [
    {
      id: "node-classify",
      label: "Classify",
      subtitle: "One active PR → packet",
      kind: "agent",
      position: { x: 0, y: 160 },
      entityId: "agent-renovate-classifier",
      relatedProjectSlug: "renovate-governance",
    },
    {
      id: "node-route",
      label: "Route",
      subtitle: "Auto / investigate / stop",
      kind: "workflow",
      position: { x: 260, y: 160 },
      entityId: "workflow-renovate-ladder",
      relatedProjectSlug: "renovate-governance",
    },
    {
      id: "node-investigate",
      label: "Investigate",
      subtitle: "High-touch / unlisted",
      kind: "agent",
      position: { x: 560, y: 0 },
      entityId: "agent-renovate-investigator",
      relatedProjectSlug: "renovate-governance",
    },
    {
      id: "node-maintainer",
      label: "Maintainer",
      subtitle: "Re-verify + execute",
      kind: "agent",
      position: { x: 560, y: 320 },
      entityId: "agent-renovate-maintainer",
      relatedProjectSlug: "renovate-governance",
    },
    {
      id: "node-merge-gates",
      label: "Merge gates",
      subtitle: "Policy + CI + merge commit",
      kind: "governance",
      position: { x: 840, y: 160 },
      entityId: "governance-merge-gates",
      relatedProjectSlug: "renovate-governance",
    },
  ],
  edges: [
    { id: "e-reno-1", source: "node-classify", target: "node-route" },
    {
      id: "e-reno-2",
      source: "node-route",
      target: "node-investigate",
      label: "Investigate",
      sourceHandle: "out-top",
      targetHandle: "in",
    },
    {
      id: "e-reno-3",
      source: "node-route",
      target: "node-maintainer",
      label: "Auto path",
      sourceHandle: "out-bottom",
      targetHandle: "in",
    },
    {
      id: "e-reno-4",
      source: "node-investigate",
      target: "node-maintainer",
      label: "After audit",
      sourceHandle: "out-bottom",
      targetHandle: "in-top",
    },
    {
      id: "e-reno-5",
      source: "node-maintainer",
      target: "node-merge-gates",
      sourceHandle: "out",
      targetHandle: "in",
    },
  ],
};

const workflowEditorial: WorkflowView = {
  id: "workflow-editorial",
  title: "Editorial field-report pipeline",
  summary:
    "Capture → triage → schedule → refresh → context → draft → critique → sync → human publish. Full editorial skill chain.",
  talkTrack:
    "Walk the full operator skills: Capture grounds Notion Inbox cards; Triage promotes Candidates; Schedule picks one Drafting card; Refresh is optional freshness; Context gathers evidence before Draft; Critique analyzes before it scores; Sync only creates a DEV draft — humans own live publish.",
  nodes: [
    {
      id: "node-refresh",
      label: "Refresh",
      subtitle: "Optional freshness",
      kind: "skill",
      position: { x: 660, y: 0 },
      entityId: "skill-editorial-refresh",
      relatedProjectSlug: "editorial-workflow",
    },
    {
      id: "node-capture",
      label: "Capture",
      subtitle: "Create / enrich Inbox",
      kind: "skill",
      position: { x: 0, y: 160 },
      entityId: "skill-editorial-inbox",
      relatedProjectSlug: "editorial-workflow",
    },
    {
      id: "node-triage",
      label: "Triage",
      subtitle: "Inbox → Candidate",
      kind: "skill",
      position: { x: 220, y: 160 },
      entityId: "skill-editorial-triage",
      relatedProjectSlug: "editorial-workflow",
    },
    {
      id: "node-schedule",
      label: "Schedule",
      subtitle: "Candidate → Drafting",
      kind: "skill",
      position: { x: 440, y: 160 },
      entityId: "skill-editorial-scheduler",
      relatedProjectSlug: "editorial-workflow",
    },
    {
      id: "node-context",
      label: "Context",
      subtitle: "Bounded evidence packet",
      kind: "skill",
      position: { x: 880, y: 160 },
      entityId: "skill-editorial-context",
      relatedProjectSlug: "editorial-workflow",
    },
    {
      id: "node-draft",
      label: "Draft",
      subtitle: "Repo markdown body",
      kind: "skill",
      position: { x: 0, y: 360 },
      entityId: "skill-editorial-draft",
      relatedProjectSlug: "editorial-workflow",
    },
    {
      id: "node-critique",
      label: "Critique",
      subtitle: "Analyze before score",
      kind: "skill",
      position: { x: 260, y: 360 },
      entityId: "skill-editorial-critique",
      relatedProjectSlug: "editorial-workflow",
    },
    {
      id: "node-sync",
      label: "Sync",
      subtitle: "DEV draft only",
      kind: "skill",
      position: { x: 520, y: 360 },
      entityId: "skill-editorial-publish",
      relatedProjectSlug: "editorial-workflow",
    },
    {
      id: "node-publish",
      label: "Publish",
      subtitle: "Human-approved live post",
      kind: "output",
      position: { x: 780, y: 360 },
      entityId: "output-dev-field-reports",
      relatedProjectSlug: "editorial-workflow",
    },
  ],
  edges: [
    { id: "e-edit-1", source: "node-capture", target: "node-triage" },
    { id: "e-edit-2", source: "node-triage", target: "node-schedule" },
    {
      id: "e-edit-3",
      source: "node-schedule",
      target: "node-refresh",
      label: "Optional",
      sourceHandle: "out-top",
      targetHandle: "in-bottom",
    },
    {
      id: "e-edit-4",
      source: "node-refresh",
      target: "node-context",
      sourceHandle: "out",
      targetHandle: "in-top",
    },
    {
      id: "e-edit-5",
      source: "node-schedule",
      target: "node-context",
      label: "Skip",
      sourceHandle: "out",
      targetHandle: "in",
    },
    {
      id: "e-edit-6",
      source: "node-context",
      target: "node-draft",
      sourceHandle: "out-bottom",
      targetHandle: "in-top",
    },
    { id: "e-edit-7", source: "node-draft", target: "node-critique" },
    {
      id: "e-edit-8",
      source: "node-critique",
      target: "node-draft",
      label: "Revise",
      sourceHandle: "out-bottom",
      targetHandle: "in-bottom",
    },
    {
      id: "e-edit-9",
      source: "node-critique",
      target: "node-sync",
      label: "Ready",
    },
    {
      id: "e-edit-10",
      source: "node-sync",
      target: "node-publish",
      label: "Human",
    },
  ],
};

export const projectWorkflowViewsBySlug: Record<string, WorkflowView> = {
  "editorial-workflow": workflowEditorial,
  "renovate-governance": workflowRenovate,
};
